### ISSUE TITLE
Support metas in peeled syntax

### ISSUE THREAD

**Issue by fizruk** [objectionary/eo-phi-normalizer#111]
> Both this and previous lines should be updated, but in a separate PR, one that introduces meta variables and meta functions in the syntax for peeled objects. This is of low priority for now.

_Originally posted by @fizruk in https://github.com/objectionary/normalizer/pull/105#discussion_r1485613042_

**Comment by Anatolay** [comment]
[Current rules](https://github.com/objectionary/eo-phi-normalizer/blob/6e3b8b0a8229769e9e45b671cb39654c8060c61b/eo-phi-normalizer/test/eo/phi/rules/yegor.yaml#L1) do not deal with head-tail representation of objects. Thus, the peel functions are not used (and do not seem to be planned). Closing this.
