### ISSUE TITLE
Implement the optimization for the Spring application as custom rule(s)

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#257]
## Details

Normalizer should optimize Factorial calculation via custom rules.

### Questions

- Which optimization should be used for the application?

## Subtasks

- [ ] Implement the optimization as a custom rule.

**Comment by deemp** [comment]
@maxonfjvipon @volodya-lombrozo, which optimization should be used for the Spring application?

**Comment by fizruk** [comment]
I think this must be closed now, in favor of #470. Feel free to reopen if necessary.
