### ISSUE TITLE
Draft a paper

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#38]
- [ ] What is the research question? 
- [ ] Global contribution?
- [ ] Look at the context 
  - [ ] state-of-the-art imperative systems
  - [ ] rewrite systems

**Comment by Anatolay** [comment]
Which paper is meant here? Is it the one for [the proof of confluence](https://github.com/objectionary/proof)?

**Comment by deemp** [comment]
Yes, that one
