### ISSUE TITLE
Implement pre-defined rules from Yegor's paper

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#4]
- [ ] Implement rules from Yegor's [paper](https://github.com/yegor256/phi-paper/blob/fcbebe4a9e442170966c82dc0925130e9c90548c/main.pdf)
  ![image](https://github.com/objectionary/normalizer/assets/48378098/e4a099c9-1e8d-4e35-86b8-e360b834c467)
  - [x] R1 (#9)
  - [ ] R2
  - [ ] R3
  - [ ] R4
  - [ ] R5
  - [x] R6 (#9)
  - [ ] R7
  - [ ] R8
  - [ ] R9
  - [ ] R10
  - [ ] R11
  - [ ] R12

**Comment by deemp** [comment]
@fizruk, is this still necessary?

**Comment by deemp** [comment]
@fizruk, is this issue still necessary?

**Comment by Anatolay** [comment]
Closing it as
- The rules here are outdated,
- New rules seem to be [implemented](https://github.com/objectionary/eo-phi-normalizer/blob/6e3b8b0a8229769e9e45b671cb39654c8060c61b/eo-phi-normalizer/test/eo/phi/rules/yegor.yaml#L1).
