### ISSUE TITLE
let's add copyrights checker to CI pipeline

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#450]
## Details

See, how it's done here: https://github.com/objectionary/eo/blob/master/.github/workflows/copyrights.yml

## Subtasks

- [x] Add the action (https://github.com/objectionary/eo-phi-normalizer/pull/534)
- [ ] https://github.com/objectionary/eo-phi-normalizer/issues/535

**Comment by yegor256** [comment]
@deemp please, consider this

**Comment by deemp** [comment]
@yegor256, please write:
- motivation for this proposal
- list of regexes for file names that we should check

**Comment by yegor256** [comment]
@deemp it's mostly a matter of discipline. If every file has a copyright notice in front of it, this will guarantee that when this particular file is found somewhere outside of this repository, it will be clear who created it and who can use/copy it. I suggest checking all text files, including `.yaml`, `.hs`, and every other format you can annotate with a license.

**Comment by yegor256** [comment]
@deemp use the one I added to the root directory: https://github.com/objectionary/normalizer/blob/master/LICENSE.txt

**Comment by deemp** [comment]
@yegor256, should we write copyright notices in generated `.phi` files ([example](https://github.com/objectionary/eo-phi-normalizer/blob/master/eo-phi-normalizer/data/0.38.4/org/eolang/as-phi.phi))?

**Comment by yegor256** [comment]
@deemp we don't support comments in `.phi` format now (and will not support them in future, I believe)

**Comment by deemp** [comment]
@yegor256, got it. I think we shouldn't support them too ([we currently do](https://github.com/objectionary/eo-phi-normalizer/blob/c53ed6a49b5632c4eed7cc347d1fb3bfc1f7361e/eo-phi-normalizer/grammar/EO/Phi/Syntax.cf#L7-L8)).

**Comment by deemp** [comment]
@yegor256, this issue is about adding a checker. Another issue is about adding copyright notices. 

These are different tasks, so each deserves a separate issue.
