### ISSUE TITLE
Support printing rules in LaTeX

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#471]
## Details

We want to compare rules in the [phi-paper](https://github.com/yegor256/phi-paper) and rules in the `normalizer` repo ([yegor.yaml](https://github.com/objectionary/normalizer/blob/520529cca4eefe3a713abb5c83c729dfc97e85a2/eo-phi-normalizer/test/eo/phi/rules/yegor.yaml)).

### Acceptance criteria

1. Given the rules are in the [yegor.yaml](https://github.com/objectionary/normalizer/blob/520529cca4eefe3a713abb5c83c729dfc97e85a2/eo-phi-normalizer/test/eo/phi/rules/yegor.yaml) file, when I run `normalizer print-rules --tex eo-phi-normalizer/test/eo/phi/rules/yegor.yaml`, then the `normalizer` prints the rules in LaTeX format.

## Subtasks

- [x] Add the command `print-rules` with the `--tex` option
- [x] Print LaTeX for this command with this option

**Comment by deemp** [comment]
@yegor256, please provide the LaTeX output for a rule in `yegor.yaml`

**Comment by yegor256** [comment]
@deemp just put every rule in to a new line, listing 1) the pattern, 2) the replacement, 3) all conditions. When this is renderable, please, show. I will suggest improvements, if any.
