### ISSUE TITLE
how can I install specific version?

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#502]
Currently, the [instructions](https://www.objectionary.com/normalizer/docs/installation.html?highlight=update#install-normalizer-from-hackage) don't explain how to install a specific version of the package. I need to install version 1.1.0, for example. Please, update the instructions, if possible.

**Comment by yegor256** [comment]
@deemp please, help

**Comment by deemp** [comment]
@yegor256, specify the version after the package name. 

Example: `stack install --resolver lts-22.16 eo-phi-normalizer-1.1.0`

I agree that we should update the documentation.

**Comment by deemp** [comment]
This command is documented now [here](https://www.objectionary.com/eo-phi-normalizer/docs/installation.html#install-eo-phi-normalizer-from-hackage).

@yegor256, please close this issue if you don't have any further questions.
