### ISSUE TITLE
Use the `eo-phi-normalizer` name

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#505]
## Details

The current name `normalizer` is very generic and conflicts with other names on my computer. Also, it doesn't match the name of the package being installed. I suggest we rename the repository too. All names should match: repo name, package name, executable name.

```
$ stack install --resolver lts-22.16 eo-phi-normalizer
Copying from /Users/yb/.stack/snapshots/aarch64-osx/f0f9482540a35cfba44bbf445a8f943dfb845f63b327440a37592df34ca4134d/9.6.4/bin/normalizer to
/Users/yb/.local/bin/normalizer.
Copied executables to /Users/yb/.local/bin/:
* normalizer

Warning: The normalizer executable found on the PATH environment variable is /Users/yb/.python3/bin/normalizer and not the version that was just installed.
         This means that normalizer calls on the command line will not use this version.
```

## Subtasks

Rename to `eo-phi-normalizer`:

- [x] [This repository](https://github.com/objectionary/normalizer)
- [x] The binary name - see https://github.com/objectionary/normalizer/issues/479

**Comment by yegor256** [comment]
@deemp please, help

**Comment by deemp** [comment]
@yegor256, I don't mind using the same name everywhere.

However, I can't rename this repository. Please rename it

**Comment by yegor256** [comment]
@deemp renamed

**Comment by deemp** [comment]
Should be resolved now. See https://github.com/objectionary/eo-phi-normalizer/issues/479
