### ISSUE TITLE
The link to documentation is broken

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#510]
## Details

Currently, in the repo description, there is a link to the project site https://www.objectionary.com/normalizer/.

The repository was recently renamed ([link](https://github.com/objectionary/eo-phi-normalizer/issues/505#issuecomment-2397296583)).

## Subtasks

- [ ] @yegor256 @fizruk  change that link to https://www.objectionary.com/eo-phi-normalizer/

**Comment by yegor256** [comment]
@deemp fixed

**Comment by 0crat** [comment]
@deemp Thank you for submitting this ticket. Unfortunately, it wasn't accepted by the team. As per our policy, this results in a **-16** point deduction. Your current balance is [+12](https://www.eolang.org/zerocracy/objectionary-vitals.html). Despite this setback, we encourage you to continue [reporting](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) issues. Remember, [bugs are welcome](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) as they help improve our project. Please review carefully before submitting future tickets. Your contributions are valuable to our team's success.
