### ISSUE TITLE
pretty printing doesn't put enough EOLs

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#545]
related to #515 

I'm getting this output:

```
...
method-params ↦ Φ.jeo.params, annotations ↦ Φ.org.eolang.seq0, φ ↦ Φ.org.eolang.seq3 (
  α0 ↦ ξ.aload-BD64, α1 ↦ ξ.invokespecial-BD66, α2 ↦ ξ.return-BD68
),
trycatchblocks-object@init@ ↦ Φ.org.eolang.seq0, local-variable-table ↦ Φ.org.eolang.seq0, aload-BD64 ↦ Φ.jeo.opcode (
  α0 ↦ Φ.jeo.int (
    α0 ↦ Φ.org.eolang.bytes (
      Δ ⤍ 00-00-00-00-00-00-00-19
    )
  ),
  α1 ↦ Φ.jeo.int (
    α0 ↦ Φ.org.eolang.bytes (
      Δ ⤍ 00-00-00-00-00-00-00-00
    )
  )
),
...
```

Obviously, a better formatting would be:

```
...
method-params ↦ Φ.jeo.params, 
annotations ↦ Φ.org.eolang.seq0, 
φ ↦ Φ.org.eolang.seq3 (
  α0 ↦ ξ.aload-BD64, 
  α1 ↦ ξ.invokespecial-BD66, 
  α2 ↦ ξ.return-BD68
),
trycatchblocks-object@init@ ↦ Φ.org.eolang.seq0, 
local-variable-table ↦ Φ.org.eolang.seq0, 
aload-BD64 ↦ Φ.jeo.opcode (
  α0 ↦ Φ.jeo.int (
    α0 ↦ Φ.org.eolang.bytes (
      Δ ⤍ 00-00-00-00-00-00-00-19
    )
  ),
  α1 ↦ Φ.jeo.int (
    α0 ↦ Φ.org.eolang.bytes (
      Δ ⤍ 00-00-00-00-00-00-00-00
    )
  )
),
```

**Comment by yegor256** [comment]
@deemp @fizruk please, check

**Comment by yegor256** [comment]
@fizruk here is a more simple example:

```
$ cat bar.phi
{⟦ m ↦ ⟦ x ↦ ξ.t, φ ↦ ⟦ t ↦ ⟦⟧ ⟧ ⟧.x ⟧}
$ eo-phi-normalizer rewrite -s bar.phi
{
  ⟦
    m ↦ ⟦
      ρ ↦ ⟦
        t ↦ ⟦ ⟧, ρ ↦ ⟦
          x ↦ ξ.t, φ ↦ ⟦
            t ↦ ⟦ ⟧
          ⟧
        ⟧
      ⟧
    ⟧
  ⟧
}
```

Obviously, the formatting is wrong.

**Comment by yegor256** [comment]
@deemp let's close it when the problem is solved _on my side_, in a new release

**Comment by deemp** [comment]
@yegor256, we've released v2.2.0 that should resolve this issue. Please check

**Comment by 0crat** [comment]
@yegor256 Thank you for your submission! Unfortunately, it wasn't accepted by the team. As per our policy, this results in a -16 point penalty. Your current balance is now [-78](https://www.eolang.org/zerocracy/objectionary-vitals.html). Don't be discouraged, though! Your efforts to improve our project's quality are valuable. Keep [reporting bugs](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) and suggesting enhancements, but try to be more thorough next time. Remember, [bugs are welcome](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) when they help us grow!

**Comment by yegor256** [comment]
@deemp this problem is gone
