### ISSUE TITLE
menu is broken on the site

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#547]
Go to https://www.objectionary.com/eo-phi-normalizer/docs/atoms.html. Click on 8.1 in the menu on the left. Then, click on "Introduction".

**Comment by yegor256** [comment]
@deemp please, check this one

**Comment by deemp** [comment]
@yegor256, reproduced, thanks. Working on it.

**Comment by deemp** [comment]
Seems to be relevant https://github.com/rust-lang/mdBook/issues/2488

**Comment by deemp** [comment]
@yegor256, the issue should be resolved. Please check the site

**Comment by yegor256** [comment]
@deemp works now, thanks!

**Comment by 0crat** [comment]
@yegor256 Hey there! 👋 Sorry to hear your ticket wasn't accepted this time. As per our policy, that's a -16 point deduction. Don't let it get you down though! Your bug reports and enhancement ideas are super valuable for improving our project. Just aim for a bit more precision next time, okay? Keep those [bug reports](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) coming - they're always [welcome](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html)! Your current balance is [-66](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the great work!

**Comment by yegor256** [comment]
@deemp next time, in order to avoid such penalties, please attach "bug" label to tickets that you believe are bugs.
