### ISSUE TITLE
how-to-contribute section is missing in the documentation

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#563]
If I'm a new contributor to the project and want to make some changes in the code and then submit a pull request, how can I build the project locally to make sure I don't break anything before committing the changes? Just an example of such a section, from our repo: https://github.com/objectionary/eo?tab=readme-ov-file#how-to-contribute

Maybe you can even follow the GitHub guidelines: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by yegor256** [comment]
@deemp see, it's very much against the common standards on GitHub, that's why I didn't find it. This block should either be in the README (like we do) or in the `CONTRIBUTING.md` file (like GitHub recommends).

**Comment by deemp** [comment]
@yegor256, the contributing doc is quite big, so putting it into `CONTRIBUTING.md` seems to be the right option.

**Comment by deemp** [comment]
@yegor256, the [CONTRIBUTING.md](https://github.com/objectionary/eo-phi-normalizer/blob/master/CONTRIBUTING.md) section is in `master`.

**Comment by yegor256** [comment]
@deemp perfect, thanks!
