### ISSUE TITLE
the output is not escaped on error

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#572]
I see this in the log:

```
$ eo-phi-normalizer rewrite --rules 0.yml Foo.phi --single -o Bar.phi
eo-phi-normalizer: syntax error at line 1, column 1 due to lexer error
on input
?.org.eolang.bytes ( ?0 ? ? ? ? 00-00-00-00-00-00-1E-61 ? )
```

Here, I don't understand whether the problem is with the encoding or the input was indeed formatted as `?0` instead of `α0`. I suggest you to "escape" non-ASCII symbols in the output. Instead of printing UTF-8 as is, convert them to something like `\u045e`.

Maybe you can say `on input (non-ASCII symbols escaped)` instead of just `on input`.

**Comment by yegor256** [comment]
@deemp please, help

**Comment by deemp** [comment]
@yegor256, run `export LC_ALL=C.UTF-8` before running this command.

**Comment by yegor256** [comment]
@deemp yes, we know the workaround, but please make the output escaped :)

**Comment by deemp** [comment]
@yegor256, 

1. Does normalizer render Unicode in error messages with `export ...`? 
1. Does normalizer render Unicode in normal output without `export ...`?  If it doesn't, then `export ...` is not a workaround, but a necessity. We can write it explicitly on the command pages.

**Comment by yegor256** [comment]
@deemp yes, it works with the `export`, but I kindly ask you to implement this escaping feature because it will help users debug much faster

**Comment by deemp** [comment]
@yegor256, it's inconvenient to read numbers when you can read Unicode characters. If the locale is set correctly, users may prefer to see Unicode.

**Comment by yegor256** [comment]
@deemp I'm the primary user of this app :) I'm telling you, as a user, that error messages must be as non-ambiguous as possible. Unicode is more ambiguous than ASCII.

**Comment by deemp** [comment]
@yegor256

Here's how errors look like now (with simplest escaping):

```
syntax error at line 1, column 1 before `\961'
on input
\961 \8614 \10214 t \8614 \958.\961.k.\961.t
```

Here's how they looked before when the correct locale was enabled:

```
syntax error at line 1, column 1 before `ρ'
on input
ρ ↦ ⟦ t ↦ ξ.ρ.k.ρ.t
```

Do you really prefer the option with escaping?

**Comment by yegor256** [comment]
@deemp can you do both? show the original one and then print the escaped one?

**Comment by deemp** [comment]
> the original one

@yegor256, which one do you mean?

**Comment by yegor256** [comment]
@deemp how many do you have? :) print them both

**Comment by deemp** [comment]
@yegor256, see https://github.com/objectionary/eo-phi-normalizer/issues/572#issuecomment-2508009676

**Comment by yegor256** [comment]
@deemp please, print both outputs in case of error: 1) not escaped, and 2) escaped

**Comment by deemp** [comment]
@yegor256

Platform: Linux

Input program: `ξ.a.b(c ↦ ⟦ Δ ⤍ 3F-FC ⟧)`

1. Not escaped, `export LANG=en_US.UTF-8`:

```
eo-phi-normalizer: An error occurred when parsing the input program:
syntax error at line 1, column 1 before `'
on the input:
.a.b(c     3F-FC )
```

1. Not escaped, `export LANG=C.UTF-8`:

```
eo-phi-normalizer: An error occurred when parsing the input program:
syntax error at line 1, column 1 before `ξ'
on the input:
ξ.a.b(c ↦ ⟦ Δ ⤍ 3F-FC ⟧)
```

1. Non-ASCII escaped (Unicode characters replaced with their numbers), LANG doesn't matter:

```
eo-phi-normalizer: An error occurred when parsing the input program:
syntax error at line 1, column 1 before `\961'
on the input:
\961 \8614 \10214 t \8614 \958.\961.k.\961.t
```

**Comment by yegor256** [comment]
@deemp the first option is not "escaping" but "removing" :) please, use option two and option three together

**Comment by deemp** [comment]
@yegor256, I've implemented in https://github.com/objectionary/eo-phi-normalizer/pull/590 a way to always use the option 2 despite the locale. The `eo-phi-normalizer` will set the locale on its own as well as the code page on Windows.

We'll soon make a release where this functionality is supported.

**Comment by yegor256** [comment]
@deemp cool, thanks!
