### ISSUE TITLE
let's add `--oneline` option to the `rewrite` command

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#580]
Now, the `rewrite` command produces a pretty-printed formula. Sometimes it's more desirable (especially for tests) to get it in one line. Let's add `--oneline` option, making it print the entire formula in one line.

**Comment by yegor256** [comment]
@deemp please, help

**Comment by deemp** [comment]
@yegor256, please provide some examples of single-line output.

**Comment by deemp** [comment]
@yegor256, is this output OK?

```
{ ⟦ c ↦ Φ.org.eolang.float ( as-bytes ↦ Φ.org.eolang.bytes ( Δ ⤍ 40-39-00-00-00-00-00-00 ) ), result ↦ ξ.c.times ( x ↦ ⟦ Δ ⤍ 3F-FC-CC-CC-CC-CC-CC-CD ⟧ ) .plus ( x ↦ ⟦ Δ ⤍ 40-40-00-00-00-00-00-00 ⟧ ), λ ⤍ Package ⟧ }
```

**Comment by deemp** [comment]
I'll merge https://github.com/objectionary/eo-phi-normalizer/pull/588 and make a release, and we can discuss further changes then.

**Comment by yegor256** [comment]
@deemp yes, looks good

**Comment by yegor256** [comment]
@deemp works fine in 2.2.2, thanks!
