### ISSUE TITLE
TeX output is broken when `--chain` is not used

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#596]
When I use `rewrite` with the `--chain` argument, the output is in TeX. However, without the `--chain`, the output contains old/broken format:

```
$ cat bar.phi
{⟦ m ↦ ⟦ x ↦ ⟦ t ↦ ⟦ Δ ⤍ 42- ⟧ ⟧.t ⟧.x ⟧}
/code/tmp/eo$ eo-phi-normalizer rewrite --tex bar.phi
Rule set following Nov 2024 revision
[[ m -> [[ ^ -> [[ t -> [[ D> 42- ]] ]], D> 42- ]] ]]
```

The same (complete and well formatted TeX) must printed instead.

Related to #573

**Comment by yegor256** [comment]
@deemp please, check

**Comment by deemp** [comment]
@yegor256, which output do you expect?

**Comment by deemp** [comment]
@yegor256, please check v2.3.0

**Comment by yegor256** [comment]
@deemp works perfectly, thanks!
