### ISSUE TITLE
Support all Yegor's rules as user-defined

### ISSUE THREAD

**Issue by fizruk** [objectionary/eo-phi-normalizer#62]
The rules are being implemented in [`eo-phi-normalizer/test/eo/phi/rules/yegor.yaml`](eo-phi-normalizer/test/eo/phi/rules/yegor.yaml):

- [x] Rule 1
  - requires #55, #56, #57, #58. Implemented in #105
- [x] Rule 2
  - requires #55. Implemented in #112
- [x] Rule 3
  - requires #55
- [x] Rule 4
  - ~~requires #57~~. Implemented in #99
- [x] Rule 5
  - ⚠️ implemented, but does not work properly (needs to be updated)
- [x] Rule 6
  - ⚠️ implemented, but does not work properly due to questionable normal form condition
- [x] Rule 7
  - ⚠️ implemented without vertex attribute, but does not work properly (updates to $\xi$, $\sigma$ and $\rho$ attributes
- [x] Rule 8
  - requires #55
- [x] Rule 9 (implemented in a slightly different form, but equivalent)
- [x] Rule 10
  - ~~requires #56~~. Implemented in #80
- [x] Rule 11
  - requires #55
- [x] Rule 12
  - Implemented in #109

**Comment by deemp** [comment]
What version of rules?

**Comment by aabounegm** [comment]
I based my work on the lastest version sent on the Telegram group:
![telegram-cloud-photo-size-2-5318754811103008537-y](https://github.com/objectionary/normalizer/assets/11016151/14916182-339b-41c7-b097-31a4a0c28a4e)

**Comment by fizruk** [comment]
I think all rules are now implemented (more or less faithfully). Now it is time to cover with tests and collect metrics.
