### ISSUE TITLE
the description of dataization process is outdated

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#631]
What I read here (https://www.objectionary.com/eo-phi-normalizer/docs/eo-phi-normalizer/dataize.html) is not accurate, both in the terminology it uses (what is "empty binding" or "value"?) and the process explained ("If the object is a formation that contains a ϕ-binding and no empty bindings, the result becomes the dataization of its attached object" -- this is not true, according to the current rules).

I suggest removing this description entirely, since it duplicates the content of the paper we have about and only confuses the reader. Let's just focus on the functionality of normalizer, leaving the logic of normalization to the rules, which are explained in the YAML file.

**Comment by deemp** [comment]
@yegor256, I agree that the `Dataization process` section should be removed.
