### ISSUE TITLE
Add ruleset feature: conflict resolution rules

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#64]
## Details

Some rules may produce the existing attribute names, thus creating naming conflicts.

Hence, we need some rules to resolve such conflicts.

## Subtasks

- [ ] support naming conflict resolution rules
- [ ] support importing these rules

    ```yaml
    conflicts:
    - not_allowed_names
    - conflict_resolution_1.yaml
    ```

**Comment by Anatolay** [comment]
@deemp what is meant by conflict resolution?

- Does it refer to importing several rulesets?
- Does it refer to a case where two or more rules can be applied to the same term?

Is it still planned? Should I close it?

**Comment by fizruk** [comment]
This is obsolete, as #432 adds proper support for fresh attribute names.
